# Name your project!
name: 'dbt_pipeline'
version: '1.0.0'

profile: 'dbt_pipeline'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
models:
  dbt_pipeline:
    # This tells dbt to use Unity Catalog instead of Hive Metastore
    +catalog: dbt_test1 
    
    bronze:
      +materialized: table
      +schema: bronze    # Added + prefix to fix warning
    silver:
      +materialized: table
      +schema: silver    # Added + prefix to fix warning
    gold:
      +materialized: table
      +schema: gold      # Added + prefix to fix warning
