version: 2

sources:
  - name: landing_zone
    description: "Raw CSVs landing in Databricks Volumes"
    database: main
    schema: volume
    loader: read_files
    tables:
      # Dimensions (Full Load)
      - name: customers
      - name: products
      - name: categories
      
      # Facts (Incremental/Streaming)
      - name: orders
      - name: payments