version: 2

sources:
  - name: landing_zone
    description: "Raw CSVs landing in Databricks Volumes"
    database: dbt_test1
    schema: bronze
    loader: read_files
    tables:
      - name: customers
      - name: orders

  - name: source
    database: dbt_test1
    schema: default
    tables:
      - name: test_json